* Analysis of Trends;
*SUMMARY STATISTICS;
proc freq data=lmt.job_data;
    tables Job_Title Job_ID Date_Posted Date_Updated  
    Status Job_Type Skills Dept Location Sal_Range / missing;
run;
data  let.data_split;
  set let.job_data;
  /* Extract minimum and maximum sal values */ 
  sal_Min = scan(sal_Range, 1, '-');
  sal_Max = scan(sal_Range, 2, '-');
run;
proc means data=let.data_means chartype min max var range vardef=df;
	var Min_Sal Max_Sal;
	class Location dept Skills Job_Type;
run;
proc univariate data=let.data_means vardef=df noprint;
	var Min_Sal Max_Sal;
	class Location dept Skills Job_Type;
	histogram Min_Sal Max_Sal;
	inset min max var range / position=nw;
run;
proc sort data=let.data_means out=_null_;
	by Location;
run;

*Charts and Visualisations;
proc boxplot data=let.data_means;
	plot (Min_Sal Max_Sal)*Location / boxstyle=schematic;
	inset min max / position=nw;
run;
proc sort data=let.data_means out=_null_;
	by Skills;
run;
proc boxplot data=let.data_means;
	plot (Min_Sal Max_Sal)*Skills / boxstyle=schematic;
	inset min max / position=nw;
run;
*Heat Map of Jobs by Location and Job Type;
proc sgplot data=let.data_means; 
heatmap x=location y=job_type / colorresponse=max_sal; 
title "Average sal by Location and Job Type"; 
run;
*Bar Chart- sal based on dept, location, skills, job type;
ods graphics / reset width=6.4in height=4.8in imagemap;
proc sgplot data=let.DATA_SPLIT;
	vbar dept / group=sal_Max groupdisplay=cluster stat=percent;
	yaxis grid;
run;
ods graphics / reset;

* VISUALISATIONS ;
*Max Sal Based on Locations;
ods graphics / reset width=4in height=4in imagemap;
proc sgplot data=let.data_means;
	title height=10pt "Maximum Salaries Based on Locations";
	scatter x=Location y=sal_Max / group=dept;
run;
ods graphics / reset;
title;
proc arima data=temp plots=all;
	identify var=Max_Sal;
	estimate method=ML;
	forecast lead=15 back=0 alpha=0.05 id=Date_Posted interval=second;
	outlier;
	by Skills;
	run;
quit;
